### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by StarryN** [zivy/LSQRRecipes#1]
Hi~   
In the file "Line2DParametersEstimator.cxx", Is there anything wrong with the formula at 89th line?
`double lambda1 = (covMat11 + covMat22 + sqrt((covMat11-covMat22)*(covMat11-covMat22) + 4*covMat12*covMat12)) / 2.0;`
May be:
`double lambda1 = (covMat11 + covMat22 + sqrt((covMat11-covMat22)*(covMat11-covMat22) + 4*covMat12*covMat21)) / 2.0;`

**Comment by zivy** [comment]
@StarryN,
The expressions are equivalent as the covariance matrix is symmetric, covMat12==covMat21, so both lines of code are correct. I just chose to multiply covMat12 with itself. 

Is the question due to an error you encountered in a computation or were just looking at the code and weren't sure it was correct?

**Comment by StarryN** [comment]
Thanks for your reply!
I just read your code and  be confused about this formula. And I realized my mistake.
